### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by johanneswilm** [zotero/citeproc-node#30]
As mentioned in https://github.com/Juris-M/citeproc-js-simple/issues/1 , there are currently two packages of citeproc on npmjs and both of them are outdated. Additionally, the descriptions of the packages are unclear about the difference between them is.

**Comment by dstillman** [comment]
https://github.com/zotero/citeproc-node/issues/28

**Comment by johanneswilm** [comment]
@dstillman I don't see much of a connection between the two issues, just follow the link above.  This issue was about the corresponding npm package being out of date. Even the link used on npm is dead. See https://www.npmjs.com/package/citeproc-js-node . There is no response on the email mentioned there for maintenance use.

Could you reopen the issue or should I file another about this?

**Comment by dstillman** [comment]
But the real issue is just that the name of this repo — for a CSL-enabled HTTP API, with the use of citeproc-js rather incidental — should change, and the npm package should be changed to match. That'll happen at the same time.

**Comment by johanneswilm** [comment]
@dstillman I think they are both "real" issues. A random person on the net who doesn't know anything about zotero and just goes looking for citeproc-js on will find the outdated package with a dead link and an unresponsive email I mentioned above. This should be fixed.

I understand that additionally you re thinking about splitting this repository into two parts in issue #28 and that only one of the will be relevant for the person looking for citeproc and that that will be the repo that will inherit the package.json from what is currently a mixed repo. So this is also relevant, but unless you are thinking of doing this really soon, I think you should be updating the information on npmjs before that.

**Comment by dstillman** [comment]
I checked with @fcheslack — the citeproc-js-node NPM package you're referring to isn't actually even from this repo. This repo, which needs to be renamed, is for a citeproc-js–based HTTP server. @fcheslack put the citeproc-js-node NPM package up in response to a user request before @fbennett had a proper citeproc-js package up. It can probably be removed now, but that's @fcheslack's department.

**Comment by fbennett** [comment]
@dstillman Thanks for posting -- looks like it's time for some cleanup on the `npm` front. I'm in touch with all parties in the circle, and we'll get it sorted soon.

**Comment by johanneswilm** [comment]
@dstillman Ah, I see. This repo looked like it could have been the repo with a dead repo link, but apparently I was wrong. I am glad we've gotten a hold of you guys though!
